### ISSUE TITLE
TODO maine

### ISSUE THREAD

**Issue by Cr-N** [Cr-N/Ftc-off-season-Bit-Mo#19]
- [x]  auto red short complet

- [x] test pt stack short red

- [x] parametrizare long Red tot

- [x] incercare asta: https://rr.brott.dev/docs/v1-0/guides/extra-correction/

@Cr-N @raspbian146 @Iuli1234
